language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
script:
  - docker build -t back .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag backend $DOCKER_USER/backend:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/backend:$TRAVIS_BUILD_NUMBER
  - docker tag backend $DOCKER_USER/backend:latest
  - docker push $DOCKER_USER/backend:latest